In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0], [1.2, 104.0, 52.0, 8.0], [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis = 0)
#axis = 0 means sum vertically, axis = 1 sums horizontally
print(cal)

[ 59.  239.  155.4  76.9]


In [9]:
#reshape commands runs in O(1) time, so dont be shy to use it
#we can use it to make sure the matrix is the size we want it to be
percentage = 100 * A/cal.reshape(1, 4)
#this is an example of broadcasting, we divided the 3, 4 matrix by a 1, 4 matrix
#basically, what happens is, python auto expands the 1, 4 into a 3, 4, makes 2 more copies of it, and then each row is divided
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
