In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-1.37151259  0.16016415  1.28363509  0.32867439 -1.45424026]


In [3]:
print(a.shape)

(5,)


In [4]:
print(np.dot(a, a.T))

5.777259967786373


In [5]:
a = np.random.randn(5, 1)

In [6]:
print(a)

[[ 1.83391642]
 [ 1.49420907]
 [ 1.78101914]
 [ 1.63342593]
 [-0.837954  ]]


In [7]:
print(np.dot(a, a.T))

[[ 3.36324945  2.74025455  3.26624026  2.99556664 -1.53673761]
 [ 2.74025455  2.23266074  2.66121495  2.44067984 -1.25207847]
 [ 3.26624026  2.66121495  3.17202919  2.90916285 -1.49241212]
 [ 2.99556664  2.44067984  2.90916285  2.66808027 -1.3687358 ]
 [-1.53673761 -1.25207847 -1.49241212 -1.3687358   0.70216691]]


In [8]:
print(a.T)

[[ 1.83391642  1.49420907  1.78101914  1.63342593 -0.837954  ]]


In [ ]:
#it is better to have matrices with 5, 1 dimensions or smth like that
#matrices with dimensions like 5, or 2, give problems later on